name: 'NumenActions ChangeType'
description: 'Determine change type from commit'
runs:
  using: 'docker'
  image: 'ghcr.io/fiveateooate/numenactions:latest'
  entrypoint: '/usr/local/bin/numencli'
  args:
    - --loglevel
    - debug
    - changetype
